### ISSUE TITLE
NullPointerException when selecting a listing on the Buyer view.

### ISSUE THREAD

**Issue by lestert-nku** [lestert-nku/CSC450_GroupProject#12]
[java] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
     [java]     at edu.nku.csc450.views.AgentPanelView.selectionChanged(Unknown Source)
     [java]     at edu.nku.csc450.CustomControls.ResultPanel.mouseClicked(Unknown Source)
     [java]     at java.awt.Component.processMouseEvent(Component.java:6528)
     [java]     at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
     [java]     at java.awt.Component.processEvent(Component.java:6290)
     [java]     at java.awt.Container.processEvent(Container.java:2234)
     [java]     at java.awt.Component.dispatchEventImpl(Component.java:4881)
     [java]     at java.awt.Container.dispatchEventImpl(Container.java:2292)
     [java]     at java.awt.Component.dispatchEvent(Component.java:4703)
     [java]     at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
     [java]     at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
     [java]     at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
     [java]     at java.awt.Container.dispatchEventImpl(Container.java:2278)
     [java]     at java.awt.Window.dispatchEventImpl(Window.java:2750)
     [java]     at java.awt.Component.dispatchEvent(Component.java:4703)
     [java]     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
     [java]     at java.awt.EventQueue.access$500(EventQueue.java:97)
     [java]     at java.awt.EventQueue$3.run(EventQueue.java:709)
     [java]     at java.awt.EventQueue$3.run(EventQueue.java:703)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
     [java]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
     [java]     at java.awt.EventQueue$4.run(EventQueue.java:731)
     [java]     at java.awt.EventQueue$4.run(EventQueue.java:729)
     [java]     at java.security.AccessController.doPrivileged(Native Method)
     [java]     at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
     [java]     at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
     [java]     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
     [java]     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
     [java]     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
     [java]     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
     [java]     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
     [java]     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by celesthelost** [comment]
Fixed this pending review
